name: Static Analysis

on:
  pull_request:
    branches: ['*', '*/*']
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  eslint:
    name: ESLint

    runs-on: ubuntu-18.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install dependencies
        run: yarn install

      - name: Ensure code is linted
        run: yarn lint

  typescript:
    name: TypeScript

    runs-on: ubuntu-18.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install dependencies
        run: yarn install

      - name: Run TypeScript
        run: yarn test:typescript
